### ISSUE TITLE
free(): invalid pointer

### ISSUE THREAD

**Issue by 3togo** [vt-vl-lab/pytorch_flownet2#10]
Can anyone give me some pointers on how to debug

$ python3 demo.py 
torch.Size([1, 3, 2, 384, 512])
free(): invalid pointer
Aborted (core dumped)

**Comment by Yuliang-Zou** [comment]
What's your system configuration? Did you follow the instructions and compile the code?

**Comment by 3togo** [comment]
I follow the instructions but for torch version 0.4.1, cuda 9.0 with some very trifle modification.
https://github.com/vt-vl-lab/pytorch_flownet2/compare/master...3togo:master

**Comment by 3togo** [comment]
It crashed after running 
flownet2.cuda() in demo.py

**Comment by Yuliang-Zou** [comment]
I see. Let's set this to the v0.3.1 branch, I will set a new branch for v0.4.1 later
