### ISSUE TITLE
Zip files of pretrained models damaged

### ISSUE THREAD

**Issue by JisongXie** [vt-vl-lab/pytorch_flownet2#11]
It seems that the zip files of pretrained models have been damaged.
[Converted Caffe Pre-trained Models](https://github.com/vt-vl-lab/pytorch_flownet2#converted-caffe-pre-trained-models)
I downloaded them from google drive, and then I can't unzip them neither using unzipping software, nor the 'tar' command. They all show that the zip files have been broken. Is it the problem of my machine?

**Comment by JisongXie** [comment]
Okay, I know,  it's no need to unzip the files.

**Comment by AliKafaei** [comment]
I have the same problem, is there any way to extract them?

**Comment by JisongXie** [comment]
@AliKafaei Hello, it's no need to extract, just use it, it's already the model itself. You can see the [demo.py](https://github.com/vt-vl-lab/pytorch_flownet2/blob/master/demo.py) . It just load it directly.
`path = 'FlowNet2_src/pretrained/FlowNet2_checkpoint.pth.tar' `
 `pretrained_dict = torch.load(path)['state_dict']`
