### ISSUE TITLE
failed to extract the flow of a image with arbitrary size, e.g [600, 801]

### ISSUE THREAD

**Issue by ghost** [vt-vl-lab/pytorch_flownet2#7]
thanks for you code, but I encountered some problems, when I put 2 image with size [600, 801] to the flownet2C network, it didn't work, the error message is something like this: 
hope receive your reply, thanks:->

"
RuntimeError                              Traceback (most recent call last)
<ipython-input-404-1e9a75f82bb7> in <module>()
----> 1 flownet2(tmp)

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.pyc in __call__(self, *input, **kwargs)
    355             result = self._slow_forward(*input, **kwargs)
    356         else:
--> 357             result = self.forward(*input, **kwargs)
    358         for hook in self._forward_hooks.values():
    359             hook_result = hook(self, input, result)

/home/zlq/faster-rcnn.pytorch/FlowNet2_src/models/flownet2.pyc in forward(self, inputs)
     74 
     75         # flownetc
---> 76         flownetc_flow2 = self.flownetc(x)[0]
     77         flownetc_flow = self.upsample1(flownetc_flow2 * self.div_flow)
     78 

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.pyc in __call__(self, *input, **kwargs)
    355             result = self._slow_forward(*input, **kwargs)
    356         else:
--> 357             result = self.forward(*input, **kwargs)
    358         for hook in self._forward_hooks.values():
    359             hook_result = hook(self, input, result)

/home/zlq/faster-rcnn.pytorch/FlowNet2_src/models/components/FlowNetC.pyc in forward(self, x)
    108         out_deconv5 = self.deconv5(out_conv6)
    109 
--> 110         concat5 = torch.cat((out_conv5, out_deconv5, flow6_up), 1)
    111 
    112         flow5 = self.predict_flow5(concat5)

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 20 and 19 in dimension 2 at /pytorch/torch/lib/THC/generic/THCTensorMath.cu:111
"

**Comment by Yuliang-Zou** [comment]
Hi @zhanglanqing , check [this](https://github.com/vt-vl-lab/pytorch_flownet2/issues/2).

This one cannot handle arbitrary input size, maybe you can try the [tensorflow version](https://github.com/vt-vl-lab/tf_flownet2).
